service: geo-tesseractcollective-com

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: tesseract-admin

plugins:
  - fullstack-serverless

custom:
  fullstack:
    domain:
      - geo.tesseractcollective.com
    certificate: arn:aws:acm:us-east-1:315118507072:certificate/7b022325-a1b6-4563-878a-f4dbc91569b5
    bucketName: geo.tesseractcollective.com
    distributionFolder: static
    indexDocument: index.html
    singlePageApp: false
    noConfirm: true
