service: geo-tesseractcollective-com

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: tesseract-admin

plugins:
  - fullstack-serverless

custom:
  fullstack:
    domain:
      - geo.tesseractcollective.com
    certificate: arn:aws:acm:us-east-1:315118507072:certificate/5d45dbf5-00f3-4deb-ab7f-55a3501a26d2
    bucketName: geo.tesseractcollective.com
    distributionFolder: static
    indexDocument: index.html
    singlePageApp: false
